config/routes.rb
Rails.application.routes.draw do
  get 'gallery/' => 'gallery#index'
  get 'gallery/:id' => 'gallery#show', as: :gallery_show
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :photo_groups do
    collection do
      patch :sort
    end
  end

  resources :photos  do
    collection do
      patch :sort
    end
  end

  delete "photo_group/images/:id", to: 'photo_groups#delete_image_attachment', as: :delete_photo
  get "/pages/:page" => "pages#show"
  get "about" => "pages#show", page: "about"
  get 'photo_group/:id/photos', to: 'photo_groups#api_photos', as: :api_photos
  root "gallery#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_action :set_photo_group, only: [:show]
  layout "hello_world"

  def index
    @photo_groups = PhotoGroup.all.order(:position)
  end

  def show
      @photo_groups = PhotoGroup.all.order(:position)
      @photos = PhotoGroupSerializer.new(@photo_group).to_json
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_group
      @photo_group = PhotoGroup.friendly.find(params[:id])
    end

end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/index.html.erb
<%= render 'layouts/menu' %>
<div class="container">

<div class="row">
	<% @photo_groups.each do |group| %>

<div class="col-md-3 d-none d-md-block">
<div class="deck">
	<%= link_to gallery_show_path(group) do %>
		<%= image_tag group.group_image.variant(resize: "260x680"), :class => "grayscale" %>
	<% end %>
	<%= link_to gallery_show_path(group) do %>
		<h7><%= group.title %></h7>
	<% end %>
</div>
</div>


<% end %>
</div>

<div class="row d-md-none">
	<% @photo_groups.each do |group| %>

<div class="col-sm-12">
<div class="deck">
	<%= link_to gallery_show_path(group) do %>
		<%= image_tag group.group_image_sm.variant(resize: "260x260"), :class => "grayscale" %>
	<% end %>
	<%= link_to gallery_show_path(group) do %>
		<h7><%= group.title %></h7>
	<% end %>
</div>
</div>


<% end %>
</div>

</div>

app/views/gallery/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="mx-auto d-sm-flex d-block">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2" aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent2">
          <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link' do %>
              	9 МАРТА 2019
              	<% end %>
          </li>
          <% @photo_groups.each do |category| %>
          <li class="nav-item">
          <%= link_to gallery_show_path(category), class: 'nav-link' do %>
          <%= category.title %>
          <% end %>
          </li>
          <% end %>
          </ul>
        </div>
    </div>
</nav>
<% if user_signed_in? %>
  <%= render 'layouts/admin_menu' %>
<% end %>

<div class="container">
<p>
<strong>Альбом:</strong>
  <%= @photo_group.title %>
</p>

<%= react_component("HelloWorld", props: @photos, prerender: false) %>
</div>