config/routes.rb
Rails.application.routes.draw do
  get 'gallery/' => 'gallery#index'
  get 'gallery/:id' => 'gallery#show', as: :gallery_show
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :photo_groups do
    collection do
      patch :sort
    end
  end

  resources :photos  do
    collection do
      patch :sort
    end
  end

  delete "photo_group/images/:id", to: 'photo_groups#delete_image_attachment', as: :delete_photo
  get "/pages/:page" => "pages#show"
  get "about" => "pages#show", page: "about"
  get 'photo_group/:id/photos', to: 'photo_groups#api_photos', as: :api_photos
  root "gallery#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_one_attached :image
    belongs_to :photo_group
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include ActionController::Serialization
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :show, :index, :create, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  def sort
    params[:photo].each_with_index do |id, index|
      Photo.where(id: id).update_all(position: index + 1)
    end
  end
  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image, :width, :height, :caption, :photo_group_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.text_field :width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :photo_group_id %>
    <%= collection_select(:photo, :photo_group_id, PhotoGroup.all, :id, :title, {}, { :multiple => false } )%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Фоточки</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Фоточка</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td><%= photo.caption %></td>
        <td>
          <%= image_tag photo.image.variant(resize: "100x100") %>
        </td>
        <td><%= link_to 'Позырить', photo %></td>
        <td><%= link_to 'Редактировать', edit_photo_path(photo) %></td>
        <td><%= link_to 'Удалить', photo, method: :delete, data: { confirm: 'Удаляем, точно?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Новая фоточка', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @photo.caption %>
</p>
<% if @photo.image.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @photo.image %>
  </p>
<% end %>
<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>