config/routes.rb
Rails.application.routes.draw do
  get 'gallery/' => 'gallery#index'
  get 'gallery/:id' => 'gallery#show', as: :gallery_show
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :photo_groups do
    collection do
      patch :sort
    end
  end

  resources :photos  do
    collection do
      patch :sort
    end
  end

  delete "photo_group/images/:id", to: 'photo_groups#delete_image_attachment', as: :delete_photo
  get "/pages/:page" => "pages#show"
  get "about" => "pages#show", page: "about"
  get 'photo_group/:id/photos', to: 'photo_groups#api_photos', as: :api_photos
  root "gallery#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo_group.rb
class PhotoGroup < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_one_attached :group_image
  has_one_attached :group_image_sm
  has_many_attached :images
  has_many :photos, dependent: :destroy

  validates :title, presence: true
  validates :group_image, attached: true, size: { less_than: 10.megabytes , message: 'Слишком большой размер' }, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :group_image_sm, attached: true, size: { less_than: 10.megabytes , message: 'Слишком большой размер' }, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  # validates :images, attached: true, size: { less_than: 100.megabytes , message: 'is not given between size' }, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/photo_groups_controller.rb
class PhotoGroupsController < ApplicationController
  before_action :set_photo_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  def api_photos
      @photo_group = PhotoGroup.find(params[:id])
      @group_photos = @photo_group.photos
      render json: @group_photos
  end

  def sort
    params[:photo_group].each_with_index do |id, index|
      PhotoGroup.where(id: id).update_all(position: index + 1)
    end
  end

  def delete_image_attachment
    @image = ActiveStorage::Attachment.find_by(id: params[:id])
    puts "try delete #{@image}"
    @image.purge_later
    redirect_back(fallback_location: request.referer)
  end

  # GET /photo_groups
  # GET /photo_groups.json
  def index
    @photo_groups = PhotoGroup.all
  end

  # GET /photo_groups/1
  # GET /photo_groups/1.json
  def show
      @photki = @photo_group.photos.map { |photo| PhotoSerializer.new(photo).to_h }
      h = Hash.new
      h['images'] = @photki
      @photos = h.to_json
  end

  # GET /photo_groups/new
  def new
    @photo_group = PhotoGroup.new
  end

  # GET /photo_groups/1/edit
  def edit
  end

  # POST /photo_groups
  # POST /photo_groups.json
  def create
    @photo_group = PhotoGroup.new(photo_group_params)

    respond_to do |format|
      if @photo_group.save
        @photo_group.images.each do |img|
          photo = Photo.new(title: @photo_group.title, width: 300, height: 300, caption: '', photo_group_id: @photo_group.id)
          if photo.save
          photo.image.attach(img.blob)
          end
        end
        format.html { redirect_to @photo_group, notice: 'Фотогруппа успешно создана.' }
        format.json { render :show, status: :created, location: @photo_group }
      else
        format.html { render :new }
        format.json { render json: @photo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_groups/1
  # PATCH/PUT /photo_groups/1.json
  def update
    respond_to do |format|
      if @photo_group.update(photo_group_params)
        format.html { redirect_to @photo_group, notice: 'Фотогруппа успешно обновлена.' }
        format.json { render :show, status: :ok, location: @photo_group }
      else
        format.html { render :edit }
        format.json { render json: @photo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_groups/1
  # DELETE /photo_groups/1.json
  def destroy
    @photo_group.destroy
    respond_to do |format|
      format.html { redirect_to photo_groups_url, notice: 'Photo group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_group
      @photo_group = PhotoGroup.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_group_params
      params.require(:photo_group).permit(:title, :group_image, :group_image_sm, images: [])
    end
end

app/helpers/photo_groups_helper.rb
module PhotoGroupsHelper
end

app/views/photo_groups/_form.html.erb
<%= form_with(model: photo_group, local: true) do |form| %>
  <% if photo_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_group.errors.count, "error") %> prohibited this photo_group from being saved:</h2>

      <ul>
      <% photo_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Название фотогруппы' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label 'Обложка группы' %>
    <%= form.file_field :group_image %>
  </div>

  <div class="field">
    <%= form.label 'Обложка группы для мобилки' %>
    <%= form.file_field :group_image_sm %>
  </div>

  <div class="field">
    <%= form.label 'Фоточки:' %>
    <%= form.drag_and_drop_file_field :images, 'Кидай фоточки сюда!', size_limit: 15_000_000 ,accept: 'image/png, image/jpeg, image/gif' %>
  </div>

  <div class="actions">
    <%= form.submit 'Создать фотогруппу' %>
  </div>
<% end %>

app/views/photo_groups/edit.html.erb
<h1>Editing Photo Group</h1>

<%= render 'form', photo_group: @photo_group %>

<%= link_to 'Show', @photo_group %> |
<%= link_to 'Back', photo_groups_path %>

app/views/photo_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Фоточки</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='photo_groups' data-url="<%= sort_photo_groups_path %>">
    <% @photo_groups.each do |photo_group| %>
      <tr id=<%= dom_id(photo_group) %>>
        <td><%= photo_group.title %></td>
        <td><%= link_to 'Посмотреть', photo_group %></td>
        <td><%= link_to 'Редактировать', edit_photo_group_path(photo_group) %></td>
        <td><%= link_to 'Удалить', photo_group, method: :delete, data: { confirm: 'Точно удаляем - назад дороги нет?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить новую группу', new_photo_group_path %>

app/views/photo_groups/new.html.erb
<h1>Новая фотогруппа</h1>

<%= render 'form', photo_group: @photo_group %>

<%= link_to 'Назад к фотогруппам', photo_groups_path %>

app/views/photo_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Изменить', edit_photo_group_path(@photo_group) %> |
<%= link_to 'НАЗАД', photo_groups_path %>

<p>
  <strong>Название группы:</strong>
  <%= @photo_group.title %>
</p>

<% if @photo_group.group_image.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Обложка:</strong>
    <br>
    <%= image_tag @photo_group.group_image.variant(resize: "300x300") %>
    <br>

  </p>
<% end %>

<% if @photo_group.group_image.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Обложка для мобилки:</strong>
    <br>
    <%= image_tag @photo_group.group_image.variant(resize: "300x300") %>
    <br>

  </p>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Фоточка</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody id='photo_groups' data-url="<%= sort_photos_path %>">
  <% @photo_group.photos.each do |photo| %>
    <tr id=<%= dom_id(photo) %>>
      <td><%= photo.title %></td>
      <td><%= photo.caption %></td>
      <td>
        <%= image_tag photo.image.variant(resize: "100x100") %>
      </td>
      <td><%= link_to 'Позырить', photo %></td>
      <td><%= link_to 'Редактировать', edit_photo_path(photo) %></td>
      <td><%= link_to 'Удалить', photo, method: :delete, data: { confirm: 'Удаляем, точно?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>