config/routes.rb
Rails.application.routes.draw do
  get 'gallery/' => 'gallery#index'
  get 'gallery/:id' => 'gallery#show', as: :gallery_show
  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  resources :photo_groups do
    collection do
      patch :sort
    end
  end

  resources :photos  do
    collection do
      patch :sort
    end
  end

  delete "photo_group/images/:id", to: 'photo_groups#delete_image_attachment', as: :delete_photo
  get "/pages/:page" => "pages#show"
  get "about" => "pages#show", page: "about"
  get 'photo_group/:id/photos', to: 'photo_groups#api_photos', as: :api_photos
  root "gallery#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_menu.html.erb
<nav class="navbar navbar-expand-sm" data-toggle="affix">
    <div class="mx-auto d-sm-flex d-block flex-sm-nowrap">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarsExample1">
            <ul class="navbar-nav">
                <li class="nav-item">
                  <li class="nav-item"> <%= link_to 'Фотогруппы', photo_groups_path, class: 'nav-link' %> </li>
                  <li class="nav-item"> <%= link_to 'Фотографии', photos_path, class: 'nav-link' %> </li>
                  <li class="nav-item"> <%= link_to 'Выход из админки', destroy_user_session_path, class: 'nav-link', method: :delete %> </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_gallery_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="mx-auto d-sm-flex d-block">
          <%= link_to root_path, class: 'navbar-brand' do %>
  Andrey&Yulia
  <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2" aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent2">
          <ul class="navbar-nav">
              <li class="nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
          Главная
          <% end %>
          </li>
          <% @photo_groups.each do |category| %>
          <li class="nav-item">
          <%= link_to gallery_path(category), class: 'nav-link' do %>
          <%= category.title %>
          <% end %>
          </li>
          <% end %>
          </ul>
        </div>
    </div>
</nav>

<% if user_signed_in? %>
  <%= render 'layouts/admin_menu' %>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="mx-auto d-sm-flex d-block">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <%= link_to root_path, class: 'navbar-brand d-sm-none' do %>
          AndreYulia
        <% end %>


        <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
      	<%= link_to root_path, class: 'nav-link' do %>
      	9 МАРТА 2019
      	<% end %>
      </li>
            </ul>
        </div>
    </div>
</nav>

<% if user_signed_in? %>
  <%= render 'layouts/admin_menu' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andrey Yulia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <div class="container">
    <%= yield %>
     </div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andrey Yulia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>